#!/bin/bash

# untar openqa-perl-lib
###########################################################################
tar --skip-old-files -xf /usr/local/openqa-perl-lib.tar -C /
###########################################################################

# ready working folder
###########################################################################
mkdir -p /var/lib/openqa/images
mkdir -p /var/lib/openqa/db
mkdir -p /var/lib/openqa/pool
mkdir -p /var/lib/openqa/share/testresults
install -d -m 777 /var/lib/openqa/share/factory/iso
install -d -m 777 /var/lib/openqa/share/tests/deepin

# links
###########################################################################
ln -sfn /var/lib/openqa/share/factory /var/lib/openqa/factory
ln -sfn /var/lib/openqa/share/tests /var/lib/openqa/tests
ln -sfn /var/lib/openqa/testresults /var/lib/openqa/testresults
ln -sfn /usr/share/openqa/script /var/lib/openqa/script

# database
##########################################################################
export OPENQA_CONFIG=/etc/openqa

# populate database
# /usr/share/openqa/script/initdb --prepare_init --force
# /usr/share/openqa/script/initdb --init_database


# apache2 configure
#############################################################################
# disable the default site to release 80 port
a2dissite 000-default

# enable openqa site
cp /etc/apache2/vhosts.d/openqa.conf.template /etc/apache2/sites-available/openqa.conf
a2ensite openqa.conf

# enable the dependent mod
a2enmod headers
a2enmod proxy
a2enmod proxy_http
a2enmod proxy_wstunnel
a2enmod expires

cd /usr/lib/os-autoinst
autoreconf -f -i
./configure
make
cd -

cd /usr/lib/os-autoinst/ppmclibs
perl Makefile.PL
make
make install
cd -

service apache2 restart
